### ISSUE TITLE
Publish pre-built releases and flashing instructions

### ISSUE THREAD

**Issue by Saxin** [festlv/mavbridge#1]
Hi,

Any change to publish pre - built releases ?
Also simple flashing instructions can help.

I'm willing to give it a try.

Thanks, Eddi

**Comment by festlv** [comment]
Hi Eddi,
I've added pre-built libraries and flashing instructions here: https://github.com/festlv/mavbridge/tree/master/firmware/prebuilt-binaries

I'm only able to provide instructions for Linux and MacOS, as I don't have a Windows box to test the flashing procedure.

**Comment by Saxin** [comment]
Thanks a lot, much appreciated.
I have the esp-07, 1MB Flash, with external antenna.
Will be interesting to check range.

I see you use 4Mb modules, I guess EPS-12 / ESP-12E.
I'll try same location, hope it works on 1MB module...
x00000 rboot.bin 0x02000 rom0.bin 0x100000 spiff_rom.bin

Thanks again, Eddi
