### ISSUE TITLE
ESP-32 Support?

### ISSUE THREAD

**Issue by salocinx** [festlv/mavbridge#3]
Hi.

Thanks for the great project. I tried to flash the MavBridge project to a ESP8266 and it works really fine. However, I need to run it on a ESP32. I tried it too and flashing the ESP32 does not output any errors, but it also does not open an AP like on the ESP8266.

Any chance that you will support ESP32 in the near future? If not, some tips how to achieve would be highly appreciated : )

Best regards,
Nicolas

**Comment by festlv** [comment]
This project currently does not support ESP32. Currently I have no plans in adding the support, as I don't use mavbridge too often.

It looks like the framework/library I used when developing mavbridge does not support ESP32 either: https://github.com/SmingHub/Sming/issues/1333

**Comment by salocinx** [comment]
Thanks for your answer. I will try to substitute the Sming library with something adequate.

**Comment by faxik** [comment]
Just in case, maybe any progress was done in that direction?
